# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 5


  - name: About me
    url: "content/aboutme"
    weight: 6  


  - name: CV
    url: "content/cv"
    weight: 20


  - name: Publications
    url: "content/projects"
    weight: 30



  - name: Projects
    url: "content/projects"
    weight: 50


